# Generated by Django 5.0.2 on 2024-02-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('qty', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=1500)),
            ],
        ),
    ]
